# Generated by Django 6.0 on 2026-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
