# Generated by Django 5.2.9 on 2026-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
