# Generated by Django 5.2.9 on 2026-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_slide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Показывать заголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
