# Generated by Django 6.0.2 on 2026-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_product_is_available_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='Когда клиент хочет получить услугу', null=True, verbose_name='Дата и время записи'),
        ),
    ]
