# Generated by Django 5.2.7 on 2026-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_cartitem_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation',
            field=models.BooleanField(default=False, verbose_name='Рекомендуем'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('it', 'IT-услуги'), ('design', 'Дизайн'), ('education', 'Обучение'), ('Salads', 'Салаты'), ('Side_dishes', 'Гарниры'), ('Flour_products', 'Мучные изделия'), ('Hot_dishes', 'Горячие блюда'), ('Milk_cheese_eggs', 'Молоко, сыр, яйца'), ('Chips_snacks', 'Чипсы, снеки'), ('Water_and_drinks', 'Вода и напитки'), ('Tea_coffee_cocoa', 'Чай, кофе, какао'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('service', 'Кухня'), ('physical', 'Товар')], default='physical', max_length=20, verbose_name='Тип'),
        ),
    ]
