"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import os

from dotenv import load_dotenv
load_dotenv()
# pip install dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3_7j=2zxo2b-s08dtw8g!in4kff_4ctqbnu+(zxvqdpvrh6j%j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
  # CKEditor
    'ckeditor',
    'ckeditor_uploader',  # ← ВАЖНО: это отдельное приложение
]

# Настройки CKEditor
# Настройки CKEditor

# pip install pillow django-ckeditor
MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR/'media'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': 'uploadimage,image2',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
         'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
LOGIN_URL = 'blog:login'
LOGIN_REDIRECT_URL = 'blog:dashboard'
LOGOUT_REDIRECT_URL = 'blog:login'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

TELEGRAM_BOT_TOKEN = '7946153015:AAEJDIQbebbmttfX1jcU2wExHJ-pdUWU7VM'
TELEGRAM_CHAT_ID = 8558634705

CKEDITOR_CONFIGS = {
    'default': {
        # 'width': '100%',
        # 'height': 400,
        # 'filebrowserUploadUrl': '/ckeditor/upload/',
        # 'extraPlugins': ','.join(['image2']),  # Используем image2 вместо image
        # 'removeDialogTabs': 'image:advanced;image:Link',
        # 'image2_alignClasses': ['image-left', 'image-center', 'image-right'],
        # 'image2_disableResizer': True,
        # 'image2_prefillDimensions': False,
        # 'image2_maxSize': {'width': 800, 'height': 800},  # Максимальные размеры
        'contentsCss': ['/static/blog/css/style.css'],  # Кастомные стили
    }
}



import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # для collectstatic

# Если хотите добавить глобальную папку static (не обязательно)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # раскомментируйте, если создадите эту папку
]
# 0602 - последний шаг
# для ошибок на русском
# Язык сайта
LANGUAGE_CODE = 'ru-ru'

# Временная зона
TIME_ZONE = 'Europe/Moscow'

# Использовать интернационализацию
USE_I18N = True
USE_L10N = True
USE_TZ = True
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# В settings.py добавьте или измените следующие настройки:

# settings.py - настройки email

# Берем данные из .env файла
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# Всегда используем SMTP для Яндекс
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587  # или 465
EMAIL_USE_TLS = True  # для порта 587
# EMAIL_USE_SSL = True  # для порта 465 (используйте ТОЛЬКО один из них!)
EMAIL_TIMEOUT = 30
# От кого будут приходить письма
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = EMAIL_HOST_USER  # для системных сообщений